apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guestbook
spec:
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 6379
  type: {{ .Values.service.type }}
