apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map-internal
  namespace: customNamespaceName
data:
  nginx.conf: |
    server {
      listen 80;
      server_name nginx-internal.example.com;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }

