apiVersion: v1
kind: Pod
metadata:
  name: ubuntufleetpodhelm
  namespace: default
spec:
  containers:
  - image: ubuntu:xenial
    env:
    - name: myglobalservicetype
      value: {{ .Values.global.service }}
    imagePullPolicy: Always
    name: ubuntufleetpod 
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
